/** Domain status vocabulary. One meaning per entry — never collapse two of these. */
export const STATUS = {
  exposed: {
    key: "exposed",
    label: "Exposed in window",
    short: "Exposed",
    row: "active exposure",
    icon: "shield-alert",
    fg: "var(--status-exposed)",
    bg: "var(--status-exposed-bg)",
    border: "var(--status-exposed-border)",
    hatch: "none",
  },
  not_exposed: {
    key: "not_exposed",
    label: "Outside window",
    short: "Not exposed in window",
    row: "outside window",
    icon: "circle-check-big",
    fg: "var(--status-outside-window)",
    bg: "var(--status-outside-window-bg)",
    border: "var(--status-outside-window-border)",
    hatch: "none",
  },
  unresolved: {
    key: "unresolved",
    label: "Temporal evidence incomplete",
    short: "Temporal result unresolved",
    row: "validity missing",
    icon: "circle-question-mark",
    fg: "var(--status-unresolved)",
    bg: "var(--status-unresolved-bg)",
    border: "var(--status-unresolved-border)",
    hatch: "var(--status-unresolved-hatch)",
  },
  no_path: {
    key: "no_path",
    label: "No supporting path",
    short: "Not exposed",
    row: "no supporting path",
    icon: "circle-slash-2",
    fg: "var(--status-healthy)",
    bg: "var(--status-healthy-bg)",
    border: "var(--status-healthy-border)",
    hatch: "none",
  },
  compromised: {
    key: "compromised",
    label: "Compromised",
    short: "Compromised",
    row: "compromised version",
    icon: "shield-alert",
    fg: "var(--status-compromised)",
    bg: "var(--status-compromised-bg)",
    border: "var(--status-compromised-border)",
    hatch: "none",
  },
  neutral: {
    key: "neutral",
    label: "Neutral",
    short: "Neutral",
    row: "",
    icon: "package",
    fg: "var(--status-neutral)",
    bg: "var(--status-neutral-bg)",
    border: "var(--status-neutral-border)",
    hatch: "none",
  },
};

export const statusOf = (key) => STATUS[key] || STATUS.neutral;
